question_data = [
          {"category": "Geography",
           "type": "boolean", "difficulty": "easy",
           "question": "A group of islands is called an &#039;archipelago&#039;.",
           "correct_answer": "True",
           "incorrect_answers": ["False"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "The Republic of Malta is the smallest microstate worldwide.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "There is a city called Rome in every continent on Earth.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Alaska is the largest state in the United States.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Toronto is the capital city of the North American country of Canada.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Tokyo is the capital of Japan.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Hungary is the only country in the world beginning with H.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "New Haven is the capital city of the state of Connecticut in the United States.",
           "correct_answer": "False", "incorrect_answers": ["True"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Nova Scotia is on the east coast of Canada.",
           "correct_answer": "True", "incorrect_answers": ["False"]},
          {"category": "Geography", "type": "boolean", "difficulty": "easy",
           "question": "Rhode Island is actually located on the US mainland, despite its name.",
           "correct_answer": "True", "incorrect_answers": ["False"]}
]